### ISSUE TITLE
HeCBench: gemmEx benchmark needs support of hipblasSetIntDatatype

### ISSUE THREAD

**Issue by kballeda** [CHIP-SPV/H4I-HipBLAS#15]
gemmEx benchmark fails to work as it encounters - hipblasSetIntDatatype API, missing macro declaration.

main.cu:41:36: error: use of undeclared identifier 'HIPBLAS_INT8_DATATYPE_INT8'
    hipblasSetInt8Datatype(handle, HIPBLAS_INT8_DATATYPE_INT8);
                                   ^

**Comment by Sarbojit2019** [comment]
@kballeda, looks like HeBench is still using old hipblas. Latest hipblas has removed the interface hence no implementation. Please refer the link https://github.com/ROCmSoftwarePlatform/hipBLAS/blob/develop/CHANGELOG.md

![image](https://github.com/CHIP-SPV/H4I-HipBLAS/assets/52556743/5a7a2bbc-ebcd-4528-b7b3-08dbf873d693)
