### ISSUE TITLE
Issue with HIP 6.x API vs. HIP 5.x

### ISSUE THREAD

**Issue by colleeneb** [CHIP-SPV/H4I-HipBLAS#20]
This is in reference to:
https://github.com/CHIP-SPV/H4I-HipBLAS/blob/f67a550fc70bacbfb8ff3a0fd9d6bd2bbb563fa6/include/h4i/hipblas/impl/util.h#L12
With HIP 6.x (https://rocm.docs.amd.com/projects/HIP/en/latest/doxygen/html/structhip_pointer_attribute__t.html#hippointerattribute-t-struct-reference), `memoryType` should just be `type`. This was updated in chipStar in https://github.com/CHIP-SPV/chipStar/commit/4b80b7e94019fdfc14b7ef1382e1d990548d0d47, so hipblas doesn't build with the latest chipStar (4b80b7e94019fdfc14b7ef1382e1d990548d0d47) at the moment.

**Comment by pvelesko** [comment]
@colleeneb  fixed this in the outstanding PR branch but we need to make a more permanent fix

**Comment by Sarbojit2019** [comment]
PR is merged now. @colleeneb can you please confirm and close the ticket?

**Comment by colleeneb** [comment]
It looks like it's working indeed. Thanks @Sarbojit2019 !
