### ISSUE TITLE
Using OpenCL backend leads to an error

### ISSUE THREAD

**Issue by colleeneb** [CHIP-SPV/H4I-HipBLAS#21]
It looks like using the OpenCL backend for chipStar fails for hipBLAS. 
To reproduce: Use the `update-interop-handles` branch and see the following code:
```
#include "hipblas.h"

int main()
{

    hipblasHandle_t handle;
    hipblasCreate(&handle);
    hipblasDestroy(handle);
    return 0;
}
```
with the LZ backend this exits cleanly. With the OpenCL backend I see the following error:
```
> hipcc c.cpp  -lMKLShim -lhipblas                                                                                                                     
> ONEAPI_DEVICE_SELECTOR=opencl:gpu OCL_ICD_FILENAMES=libigdrcl.so:libintelocl.so CHIP_BE=opencl ./a.out                                                                                                                                 
terminate called after throwing an instance of 'sycl::_V1::runtime_error'
  what():  Native API failed. Native API returns: -33 (PI_ERROR_INVALID_DEVICE) -33 (PI_ERROR_INVALID_DEVICE)
```
In a test code without any hipBLAS, using ` ONEAPI_DEVICE_SELECTOR=opencl:gpu OCL_ICD_FILENAMES=libigdrcl.so:libintelocl.so CHIP_BE=opencl` works to switch to the OpenCL backend, so this is specific to hipBLAS.
 
Thanks!

**Comment by colleeneb** [comment]
It looks like this is due to https://github.com/CHIP-SPV/H4I-MKLShim/commit/08132fde814fdf25dc4ce9f3a3351d5a46663209. LZ works with the value of 6, OCL works with the value of 5. if it’s 6 with OCL then the index into backendHandles is wrong and it passes the platform_id as the device_id.

**Comment by Sarbojit2019** [comment]
@colleeneb, PR is merged with the issue you have mentioned above. Can you please check with 'develop' branch if it is working with you. if it is fixed can you close the ticket?

**Comment by colleeneb** [comment]
This is now working for me, thanks @Sarbojit2019! (just a note that hipSOLVER however is not working after https://github.com/CHIP-SPV/H4I-MKLShim/commit/95af8dd5aed2d59f362cab5a7851b61c905ce231)
